erDiagram
    PERFIL_CRIADOR {
        INT id_perfil_criador PK
        VARCHAR(150) nome_completo
        VARCHAR(120) titulo_profissional
        VARCHAR(280) bio_curta
        TEXT bio_longa
        VARCHAR(500) url_foto_perfil
        VARCHAR(254) email_contato
        VARCHAR(120) localizacao
    }

    REDE_SOCIAL {
        INT id_rede_social PK
        INT id_perfil_criador FK
        VARCHAR(15) tipo
        VARCHAR(80) nome_usuario
        VARCHAR(500) url_perfil
        int ordem_exibicao
    }

    DESTAQUE_PUBLICIDADE {
        INT id_publicidade PK
        INT id_perfil_criador FK
        VARCHAR(140) titulo
        VARCHAR(320) descricao
        VARCHAR(50) nome_empresa
        DATE data_publicidade
        INT ordem_exibicao
    }

    DESTAQUE_CONTEUDO {
        INT id_destaque_conteudo PK
        INT id_perfil_criador FK
        VARCHAR(15) tipo
        VARCHAR(140) titulo
        VARCHAR(320) descricao
        VARCHAR(500) url_externa
        INT ordem_exibicao
    }

    METRICA {
        INT id_metrica PK
        INT id_rede_social FK
        BIGINT seguidores_qtd
        BIGINT alcance_qtd
        BIGINT visualizacoes_qtd
        DECIMAL taxa_engajamento
        DECIMAL taxa_crescimento_perfil
        DATE coleta_dados_data
    }
    
    USUARIO_ADMIN {
        VARCHAR(255) hash_senha
    }

    MENSAGEM_CONTATO {
        INT id_mensagem_contato PK
        VARCHAR(120) nome
        VARCHAR(254) email_contato
        VARCHAR(140) empresa
        VARCHAR(160) assunto
        TEXT mensagem
    }
    
    PERFIL_CRIADOR ||--o{ REDE_SOCIAL : possui
    REDE_SOCIAL ||--|| METRICA : possui
    PERFIL_CRIADOR ||--o{ DESTAQUE_PUBLICIDADE : possui
    PERFIL_CRIADOR ||--o{ DESTAQUE_CONTEUDO : possui
