erDiagram
    USUARIO_ADMIN {
        VARCHAR(255) hash_senha
    }
    
    MENSAGEM_CONTATO {
        INT id_mensagem_contato PK
        VARCHAR(120) nome
        VARCHAR(254) email_contato
        VARCHAR(140) empresa
        VARCHAR(160) assunto
        TEXT mensagem
    }